"""Exports: one canonical Markdown rendering; TXT strips it, PDF styles it.
One template family, three formats — no drift between screen and export."""
import html
import re
from dataclasses import dataclass
from uuid import UUID

from app.core.exceptions import ConflictError, NotFoundError
from app.core.security import AuthUser
from app.models.action_item import ActionItem
from app.models.meeting import Meeting
from app.models.report import Report
from app.repositories.action_items import ActionItemRepository
from app.repositories.meetings import MeetingRepository
from app.repositories.reports import ReportRepository


@dataclass(frozen=True)
class ExportFile:
    filename: str
    media_type: str
    content: bytes


def render_markdown(meeting: Meeting, report: Report, items: list[ActionItem]) -> str:
    lines = [
        f"# {meeting.title}",
        "",
        f"*Meeting report - {meeting.created_at:%B %d, %Y} - "
        f"Health score: {report.health_score}/100*",
        "",
        "## Executive summary",
        "",
        report.executive_summary,
        "",
    ]
    if report.topics:
        lines += ["## Key topics", ""]
        lines += [f"- **{t.get('title')}** — {t.get('summary')}" for t in report.topics]
        lines.append("")
    if report.decisions:
        lines += ["## Decisions", ""]
        for d in report.decisions:
            by = f" _(by {d.get('made_by')})_" if d.get("made_by") else ""
            lines.append(f"- {d.get('decision')}{by}")
        lines.append("")
    if items:
        lines += [
            "## Action items",
            "",
            "| Task | Owner | Deadline | Priority | Status |",
            "|---|---|---|---|---|",
        ]
        for a in items:
            lines.append(
                f"| {a.task} | {a.owner or '—'} | {a.due_date or '—'} "
                f"| {a.priority} | {a.status.replace('_', ' ')} |"
            )
        lines.append("")
    if report.risks:
        lines += ["## Risks & blockers", ""]
        lines += [
            f"- **[{r.get('severity')}] {r.get('kind')}:** {r.get('description')}"
            for r in report.risks
        ]
        lines.append("")
    if report.open_questions:
        lines += ["## Open questions", ""]
        lines += [f"- {q.get('question')}" for q in report.open_questions]
        lines.append("")
    if report.deadlines:
        lines += ["## Deadlines", ""]
        for d in report.deadlines:
            when = d.get("date_normalized") or d.get("date_text")
            lines.append(f"- {d.get('item')} — {when}")
        lines.append("")
    if report.next_meeting_agenda:
        lines += ["## Suggested agenda for next meeting", ""]
        lines += [f"{i + 1}. {a}" for i, a in enumerate(report.next_meeting_agenda)]
        lines.append("")
    lines.append("---")
    lines.append("*Generated by MeetIQ*")
    return "\n".join(lines)


def _markdown_to_text(md: str) -> str:
    text = re.sub(r"^#{1,6}\s*", "", md, flags=re.MULTILINE)
    text = re.sub(r"\*\*?|__?|`", "", text)
    return text


def _markdown_to_html(md: str) -> str:
    """Minimal converter for our own generated markdown (headings, lists, tables)."""
    out: list[str] = []
    in_list = in_table = False
    for raw in md.splitlines():
        line = raw.rstrip()
        esc = html.escape(line)
        esc = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", esc)
        esc = re.sub(r"_(.+?)_", r"<em>\1</em>", esc)
        if line.startswith("|"):
            cells = [c.strip() for c in esc.strip("|").split("|")]
            if all(re.fullmatch(r"-{3,}", c) for c in cells):
                continue
            if not in_table:
                out.append("<table><tr>" + "".join(f"<th>{c}</th>" for c in cells) + "</tr>")
                in_table = True
            else:
                out.append("<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>")
            continue
        if in_table:
            out.append("</table>")
            in_table = False
        if line.startswith("- "):
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{esc[2:]}</li>")
            continue
        if in_list:
            out.append("</ul>")
            in_list = False
        if m := re.match(r"^(#{1,6})\s*(.*)", line):
            level = len(m.group(1))
            out.append(f"<h{level}>{re.sub(r'^#+\s*', '', esc)}</h{level}>")
        elif line == "---":
            out.append("<hr>")
        elif line:
            out.append(f"<p>{esc}</p>")
    if in_list:
        out.append("</ul>")
    if in_table:
        out.append("</table>")
    return "\n".join(out)


_PDF_CSS = """
body { font-family: 'DejaVu Sans', sans-serif; font-size: 11px; color: #18181b; margin: 36px; }
h1 { font-size: 22px; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
h2 { font-size: 14px; color: #4f46e5; margin-top: 18px; }
table { border-collapse: collapse; width: 100%; margin: 8px 0; }
th, td { border: 1px solid #d4d4d8; padding: 5px 8px; text-align: left; }
th { background: #eef2ff; }
li { margin: 3px 0; }
em { color: #52525b; }
"""


class ExportService:
    def __init__(
        self,
        meetings: MeetingRepository,
        reports: ReportRepository,
        action_items: ActionItemRepository,
    ) -> None:
        self._meetings = meetings
        self._reports = reports
        self._items = action_items

    async def export(self, user: AuthUser, meeting_id: UUID, fmt: str) -> ExportFile:
        meeting = await self._meetings.get_owned(meeting_id, user.id)
        if meeting is None:
            raise NotFoundError("Meeting not found")
        report = await self._reports.get(meeting_id)
        if report is None:
            raise ConflictError("This meeting has no report yet")
        items = await self._items.list_for_meeting(meeting_id)

        md = render_markdown(meeting, report, items)
        stem = re.sub(r"[^A-Za-z0-9-]+", "-", meeting.title.lower()).strip("-") or "meeting"

        match fmt:
            case "md":
                return ExportFile(f"{stem}.md", "text/markdown", md.encode())
            case "txt":
                return ExportFile(f"{stem}.txt", "text/plain", _markdown_to_text(md).encode())
            case "pdf":
                # Lazy import: WeasyPrint needs native libs that dev machines may lack.
                try:
                    from weasyprint import HTML
                except OSError as exc:
                    raise ConflictError(
                        "PDF export requires WeasyPrint's native libraries "
                        "(available in the Docker image)"
                    ) from exc
                body = _markdown_to_html(md)
                doc = f"<html><head><style>{_PDF_CSS}</style></head><body>{body}</body></html>"
                pdf = HTML(string=doc).write_pdf()
                return ExportFile(f"{stem}.pdf", "application/pdf", pdf)
            case _:
                raise NotFoundError(f"Unknown export format '{fmt}' (use pdf, md, or txt)")
